language: node_js
node_js: node
deploy:
  provider: heroku
  api_key: 
    secure: 
  app: powerful-waters-74865
  on:
    repo: Stelldevv/node-shopping-list-integration-tests
    branch: recipe_test
